on: [push, pull_request]
name: Run CI
jobs:
  make:
    name: Build and Upload Libhooker-Configurator
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install ldid and dpkg
        run: |
          brew install ldid dpkg
      - name: Build libhooker-configurator
        run: |
         make clean package BETA=0 DEBUG=0
         make clean package ROOTLESS=1 BETA=0 DEBUG=
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: lh-configurator
          path: packages
      
  lint:
    name: Lint libhooker-configurator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
